mysite/account/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name="user_login"),
    url(r'^blog/', auth_views.logout, name="user_logout"),
    url(r'^logout/$', auth_views.logout, {
        "template_name": "account/logout.html"}, name="user_logout"),
    url(r'^register/$', views.register, name="user_register"),
    url(r'^password-change/$', auth_views.password_change, {
        "post_change_redirect": "/account/password-change-done"},
        name="password_change"),
    url(r'^password-change-done/$', auth_views.password_change_done,
        name="password_change_done"),
    url(r'^password-reset/$', auth_views.password_reset, {
        "template_name": "account/password_reset_form.html",
        "email_template_name": "account/password_reset_email.html",
        "subject_template_name": "account/password_reset_subject.txt",
        "post_reset_redirect": "/account/password-reset-done",
    },
        name="password_reset"),
    url(r'^password-reset-done/$', auth_views.password_reset_done, {
        "template_name": "account/password_reset_done.html"},
        name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        auth_views.password_reset_confirm,
        {"template_name":"account/password_reset_confirm.html",
         "post_reset_redirect":"/account/password-reset-complete"},
        name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.password_reset_complete,
        {"template_name": "account/password_reset_complete.html"},
        name="password_reset_complete"),
    url(r'^my-information/$', views.myself, name="my-information"),
    url(r'^edit-my-information/$', views.myself_edit, name="edit-my-information"),
]

mysite/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_detail"),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    #url(r'^logout/', a)),
]

mysite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
</body>
</html>

mysite/templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.look1z.cn</p>
</div>

mysite/templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.look1z.cn">
                <img src="{% static '/images/logo.png' %}" width="100px">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">Blog</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu"
                                data-toggle="dropdown">{{ user.username }}<span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:edit-my-information' %}">编辑个人信息</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">Login</a></li>

                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>